spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercado_livro?createDatabaseIfNotExist=true
    username: root
    password: password
  jackson:
    default-property-inclusion: non-null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
